export default {
  products: [
    {
      _id: "1",
      name: "Buddhaa",
      image: "../images/img-02.jpg",
      price: 199,
      rating: 4,
      category: "Sketch",
      artist: "Ali Bakchod",
      description:
        "This is a sketch of Buddha made with Charcoal on paper on a 12x12 ft. sheet.",
      countInStock: 0,
    },
    {
      _id: "2",

      name: "Buddhaa",
      image: "../images/img-03.png",
      price: 199,
      category: "Sketch",
      rating: 4,
      countInStock: 2,
      artist: "Ali Bakchod",
    },
    {
      _id: "3",

      name: "Buddhaa",
      image: "../images/img-08.jpg",
      price: 199,
      category: "Sketch",
      rating: 4,
      countInStock: 2,
      artist: "Ali Bakchod",
    },
    {
      _id: "4",
      name: "Buddhaa",
      image: "../images/img-02.jpg",
      category: "Sketch",
      price: 199,
      countInStock: 2,
      rating: 4,
      artist: "Ali Bakchod",
    },
    {
      _id: "5",
      name: "Buddhaa",
      countInStock: 2,
      category: "Sketch",
      image: "../images/img-03.png",
      price: 199,
      rating: 4,
      artist: "Ali Bakchod",
    },
    {
      _id: "6",
      name: "Buddhaa",
      image: "../images/img-08.jpg",
      category: "Sketch",
      price: 199,
      rating: 4,
      countInStock: 2,
      artist: "Ali Bakchod",
    },
    {
      _id: "7",
      name: "Buddhaa",
      image: "../images/img-08.jpg",
      category: "Sketch",
      countInStock: 2,
      price: 199,
      rating: 4,
      artist: "Ali Bakchod",
    },
    {
      _id: "8",
      category: "Sketch",
      name: "Buddhaa",
      image: "../images/img-02.jpg",
      countInStock: 2,
      price: 199,
      rating: 4,
      artist: "Ali Bakchod",
    },
  ],
};
