export default {
  products: [
    {
      _id: "1",
      name: "Buddhaa",
      image: "../images/img-02.jpg",
      price: 199,
      rating: 4,
      category: "Sketch",
      artist: "Ali Bakchod",
      description:
        "dufhous fdbfjdsb bfeub adsbfjbj a kv adoj vjds jv dsj vjs fjov sdjo jof",
    },
    {
      _id: "2",

      name: "Buddhaa",
      image: "../images/img-03.png",
      price: 199,
      category: "Sketch",
      rating: 4,
      artist: "Ali Bakchod",
    },
    {
      _id: "3",

      name: "Buddhaa",
      image: "../images/img-08.jpg",
      price: 199,
      category: "Sketch",
      rating: 4,
      artist: "Ali Bakchod",
    },
    {
      _id: "4",
      name: "Buddhaa",
      image: "../images/img-02.jpg",
      category: "Sketch",
      price: 199,
      rating: 4,
      artist: "Ali Bakchod",
    },
    {
      _id: "5",
      name: "Buddhaa",
      category: "Sketch",
      image: "../images/img-03.png",
      price: 199,
      rating: 4,
      artist: "Ali Bakchod",
    },
    {
      _id: "6",
      name: "Buddhaa",
      image: "../images/img-08.jpg",
      category: "Sketch",
      price: 199,
      rating: 4,
      artist: "Ali Bakchod",
    },
    {
      _id: "7",
      name: "Buddhaa",
      image: "../images/img-08.jpg",
      category: "Sketch",
      price: 199,
      rating: 4,
      artist: "Ali Bakchod",
    },
    {
      _id: "8",
      category: "Sketch",
      name: "Buddhaa",
      image: "../images/img-02.jpg",
      price: 199,
      rating: 4,
      artist: "Ali Bakchod",
    },
    {
      _id: "9",
      name: "Buddhaa",
      image: "../images/img-03.png",
      category: "Sketch",
      price: 199,
      rating: 4,
      artist: "Ali Bakchod",
    },
  ],
};
